apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitalclock
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digitalclock
  template:
    metadata:
      labels:
        app: digitalclock
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: digitalclock
          image: hazrulfitri/mydigitalclock:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
